GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/61fab41a78ccd7ed572e0374

###
DELETE http://localhost:3001/api/persons/61fab41a78ccd7ed572e0374

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dan Abramov",
  "number": "12-43-234345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "342-345678"
}
